---
title: "Final-ABS"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction: 
What question are you answering with the data, and why is it important?
After looking through the questions decided 

##Prior Work/Literature Review: 
What is the current literature in this area in a few sentences regarding references that you're utilizing. It's important to cite any work that you are using if it's not your own proposal as this is best practice.

##EDA:
How did your EDA motivate your proposed methods? (This could be put in the appendix and be referenced in the main document).

##Proposed Methodology:
What are the main method(s) that you are using and why? Be sure to choose methods that are statistically appropriate for the data. State any assumptions and why they are valid.

##Analysis: 
Analyze your data and provide evaluations. What do you find (include visualization if helpful).

##Conclusion: 
What can you conclude from your analysis and how is this useful regarding the motivating question.

